"""
Subject definitions for SOS Report Analyzer.

Each subject defines a category of files to extract from the sosreport.
Edit this file to customize which files are included in each output category.

Structure:
    "key": {
        "title": "Display title for the markdown file",
        "description": "Brief description of what this category covers",
        "max_lines": 300,  # Max lines per file (default: 300, logs: 40000)
        "files": ["list", "of", "specific", "file/paths"],
        "globs": ["glob/patterns/*", "to/match/files/*"],
    }
"""

# Default limits
DEFAULT_MAX_LINES = 1500
LOG_MAX_LINES = 40000  # ~500K words at ~12 words/line

SUBJECTS = {
    "01_system_overview": {
        "title": "System Overview & Hardware",
        "description": "General system identification, hardware, BIOS, DMI, and kernel information.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "etc/redhat-release",
            "etc/os-release",
            "etc/hostname",
            "etc/machine-id",
            "proc/cpuinfo",
            "proc/meminfo",
            "proc/version",
            "proc/cmdline",
            "sos_commands/kernel/uname_-a",
            "sos_commands/kernel/sysctl_-a",
            "sos_commands/processor/lscpu",
            "sos_commands/memory/free_-m",
            "sos_commands/memory/free_-k",
            "sos_commands/hardware/dmidecode",
            "sos_commands/boot/lsinitrd",
            "sos_commands/grub2/grub2-mkconfig_--no-grubenv-update",
            "etc/default/grub",
            "etc/grub2.cfg",
            "etc/grub.d/",
            "sos_commands/date/date",
            "sos_commands/date/timedatectl",
            "sos_commands/host/hostname",
            "sos_commands/host/hostnamectl",
            "installed-rpms",
            "uname",
            "hostname",
            "uptime",
        ],
        "globs": [
            "sos_commands/kernel/*",
            "sos_commands/processor/*",
            "sos_commands/memory/*",
            "sos_commands/hardware/*",
        ],
    },
    "02_networking": {
        "title": "Networking Configuration & Status",
        "description": "IP addresses, routes, DNS, bonding, bridges, firewall rules, and network manager config.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "sos_commands/networking/ip_addr",
            "sos_commands/networking/ip_-o_addr",
            "sos_commands/networking/ip_route_show_table_all",
            "sos_commands/networking/ip_-s_link",
            "sos_commands/networking/ip_neigh_show",
            "sos_commands/networking/ss_-tpln",
            "sos_commands/networking/ss_-tupln",
            "sos_commands/networking/netstat_-s",
            "sos_commands/networking/netstat_-agn",
            "sos_commands/networking/route_-n",
            "sos_commands/networking/bridge_link_show",
            "sos_commands/networking/nmcli_gen_status",
            "sos_commands/networking/nmcli_con_show",
            "sos_commands/networking/nmcli_dev_show",
            "sos_commands/firewalld/firewall-cmd_--list-all",
            "sos_commands/firewalld/firewall-cmd_--list-all-zones",
            "sos_commands/firewalld/nft_list_ruleset",
            "sos_commands/networking/iptables_-t_filter_-vnxL",
            "etc/resolv.conf",
            "etc/hosts",
            "etc/nsswitch.conf",
            "etc/NetworkManager/NetworkManager.conf",
        ],
        "globs": [
            "sos_commands/networking/*",
            "sos_commands/networkmanager/*",
            "sos_commands/firewalld/*",
            "etc/sysconfig/network-scripts/*",
            "etc/NetworkManager/system-connections/*",
        ],
    },
    "03_storage_filesystems": {
        "title": "Storage, Filesystems & LVM",
        "description": "Block devices, mount points, LVM layout, multipath, fstab, and disk usage.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "sos_commands/block/lsblk",
            "sos_commands/block/lsblk_-f",
            "sos_commands/block/lsblk_-t",
            "sos_commands/block/blkid",
            "sos_commands/filesys/mount_-l",
            "sos_commands/filesys/df_-al",
            "sos_commands/filesys/df_-ali",
            "sos_commands/filesys/findmnt",
            "sos_commands/lvm2/pvs_-a_-v",
            "sos_commands/lvm2/vgs_-v",
            "sos_commands/lvm2/lvs_-a_-o_lv_tags_devices_lv_kernel_read_ahead_lv_read_ahead",
            "sos_commands/lvm2/vgdisplay_-vv",
            "sos_commands/lvm2/pvdisplay_-vv",
            "sos_commands/lvm2/lvdisplay_-vv",
            "sos_commands/multipath/multipath_-ll",
            "sos_commands/multipath/multipathd_show_config",
            "sos_commands/devicemapper/dmsetup_table",
            "sos_commands/devicemapper/dmsetup_info_-c",
            "etc/fstab",
            "etc/crypttab",
            "etc/lvm/lvm.conf",
            "etc/multipath.conf",
        ],
        "globs": [
            "sos_commands/block/*",
            "sos_commands/filesys/*",
            "sos_commands/lvm2/*",
            "sos_commands/multipath/*",
            "sos_commands/devicemapper/*",
            "sos_commands/scsi/*",
        ],
    },
    "04_services_boot": {
        "title": "Services, Systemd & Boot",
        "description": "Systemd units, enabled/disabled services, failed units, boot targets, and cron jobs.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "sos_commands/systemd/systemctl_list-units",
            "sos_commands/systemd/systemctl_list-units_--failed",
            "sos_commands/systemd/systemctl_list-unit-files",
            "sos_commands/systemd/systemctl_list-timers_--all",
            "sos_commands/systemd/systemctl_list-dependencies",
            "sos_commands/systemd/systemctl_show-environment",
            "sos_commands/systemd/systemctl_status_--all",
            "sos_commands/systemd/journalctl_--list-boots",
            "sos_commands/cron/crontab_-l_-u_root",
            "etc/crontab",
            "var/spool/cron/root",
        ],
        "globs": [
            "sos_commands/systemd/*",
            "sos_commands/cron/*",
            "etc/cron.d/*",
            "etc/systemd/system/*.service",
            "etc/systemd/system/*.timer",
        ],
    },
    "05_packages_subscriptions": {
        "title": "Packages, Repositories & Subscriptions",
        "description": "Installed RPMs, enabled repos, subscription manager status, and DNF/YUM configuration.",
        "max_lines": 5000,  # Package lists can be long
        "files": [
            "installed-rpms",
            "sos_commands/rpm/package-data",
            "sos_commands/yum/yum_-C_repolist",
            "sos_commands/yum/dnf_-C_repolist",
            "sos_commands/yum/yum_history",
            "sos_commands/yum/dnf_history",
            "sos_commands/subscription_manager/subscription-manager_list_--consumed",
            "sos_commands/subscription_manager/subscription-manager_list_--installed",
            "sos_commands/subscription_manager/subscription-manager_identity",
            "sos_commands/subscription_manager/subscription-manager_status",
            "sos_commands/subscription_manager/subscription-manager_facts",
            "sos_commands/subscription_manager/subscription-manager_repos_--list-enabled",
            "etc/yum.conf",
            "etc/dnf/dnf.conf",
        ],
        "globs": [
            "sos_commands/subscription_manager/*",
            "sos_commands/yum/*",
            "sos_commands/rpm/*",
            "etc/yum.repos.d/*",
        ],
    },
    "06_security_selinux": {
        "title": "Security, SELinux & Authentication",
        "description": "SELinux mode and booleans, audit rules, PAM config, SSH config, firewall, and crypto policies.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "sos_commands/selinux/sestatus_-b",
            "sos_commands/selinux/semanage_fcontext_-l",
            "sos_commands/selinux/semanage_boolean_-l",
            "sos_commands/selinux/semodule_-lfull",
            "sos_commands/auditd/auditctl_-l",
            "sos_commands/auditd/auditctl_-s",
            "etc/selinux/config",
            "etc/audit/auditd.conf",
            "etc/audit/audit.rules",
            "etc/ssh/sshd_config",
            "etc/pam.d/system-auth",
            "etc/pam.d/password-auth",
            "etc/pam.d/sshd",
            "etc/security/limits.conf",
            "etc/security/pwquality.conf",
            "etc/login.defs",
            "etc/crypto-policies/config",
            "sos_commands/crypto/update-crypto-policies_--show",
            "etc/sudoers",
        ],
        "globs": [
            "sos_commands/selinux/*",
            "sos_commands/auditd/*",
            "sos_commands/crypto/*",
            "etc/security/limits.d/*",
            "etc/sudoers.d/*",
            "etc/pam.d/*",
        ],
    },
    "07_performance_tuning": {
        "title": "Performance & Tuning",
        "description": "Tuned profiles, sysctl, resource limits, NUMA topology, IRQ balance, and scheduler settings.",
        "max_lines": DEFAULT_MAX_LINES,
        "files": [
            "sos_commands/tuned/tuned-adm_active",
            "sos_commands/tuned/tuned-adm_list",
            "sos_commands/tuned/tuned-adm_recommend",
            "sos_commands/tuned/tuned-adm_verify",
            "sos_commands/kernel/sysctl_-a",
            "proc/sys/vm/swappiness",
            "proc/sys/vm/dirty_ratio",
            "proc/sys/vm/dirty_background_ratio",
            "proc/sys/net/core/somaxconn",
            "proc/sys/net/ipv4/ip_forward",
            "proc/sys/fs/file-max",
            "proc/sys/kernel/pid_max",
            "proc/interrupts",
            "proc/softirqs",
            "sos_commands/numa/numactl_--hardware",
            "sos_commands/numa/numastat",
        ],
        "globs": [
            "sos_commands/tuned/*",
            "sos_commands/numa/*",
            "etc/tuned/*",
            "etc/sysctl.d/*",
        ],
    },
    # ---------------------------------------------------------------------------
    # Log subjects - split for maximum data in NotebookLM (500K words per source)
    # ---------------------------------------------------------------------------
    "08a_log_messages": {
        "title": "System Log - /var/log/messages",
        "description": "Main system log containing general system activity, services, and errors.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "var/log/messages",
        ],
        "globs": [],
    },
    "08b_log_dmesg": {
        "title": "Kernel Ring Buffer - dmesg",
        "description": "Kernel messages including hardware detection, driver loading, and kernel errors.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "var/log/dmesg",
            "sos_commands/kernel/dmesg",
        ],
        "globs": [],
    },
    "08c_log_secure": {
        "title": "Security Log - /var/log/secure",
        "description": "Authentication events, sudo usage, SSH logins, and security-related messages.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "var/log/secure",
        ],
        "globs": [],
    },
    "08d_log_audit": {
        "title": "Audit Log - /var/log/audit/audit.log",
        "description": "SELinux denials, syscall auditing, and security audit events.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "var/log/audit/audit.log",
        ],
        "globs": [],
    },
    "08e_log_journal": {
        "title": "Systemd Journal",
        "description": "Full systemd journal output with structured logging from all services.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "sos_commands/logs/journalctl_--no-pager",
            "sos_commands/logs/journalctl_--disk-usage",
        ],
        "globs": [
            "sos_commands/logs/*",
        ],
    },
    "08f_log_boot_cron": {
        "title": "Boot & Cron Logs",
        "description": "Boot process logs and scheduled task (cron) execution logs.",
        "max_lines": LOG_MAX_LINES,
        "files": [
            "var/log/boot.log",
            "var/log/cron",
        ],
        "globs": [],
    },
}
